### ISSUE TITLE
Is this package for 微信公众号开发者模式 or 微信开放平台第三方平台 ？ 

### ISSUE THREAD

**Issue by JJPro** [goofansu/wechat_elixir#17]
请问这个package是为 微信公众号开发者模式 还是 微信开放平台第三方平台 接入服务的？ 

Sorry for the silly question, but I couldn't make sure of it from the information provided in the Readme file. 

At first glance, it seems like is for 公众号开发者模式, because, as stated in README file, you can specify `encoding_aes_key`, which is only available in 公众号开发者模式. 

But the code also provides `Wechat.access_token` call to fetch access token, which might be a 微信开放平台第三方平台 thing. 

Please clarify, Thanks. 

Best, 
J

**Comment by goofansu** [comment]
微信公众号开发者模式 https://mp.weixin.qq.com/

**Comment by JJPro** [comment]
Okay, 谢啦。I'm looking for an Elixir lib for 微信开放平台第三方平台。
没找到。 倒是找到一个[PHP的库](https://github.com/thenbsp/wechat/wiki)，功能非常全。
看来要自己试着做了，或者选择用PHP开发。 
谢谢啦 
Best!

**Comment by goofansu** [comment]
@JJPro 你说的这个库也是公众平台，不是开放平台

**Comment by JJPro** [comment]
你确定？怎么看？

**Comment by JJPro** [comment]
哦 简介里有 
> 微信公众平台第三方

我把这句理解成开放平台第三方平台了
不好意思 打扰了
