### ISSUE TITLE
Missing source code for v0.4.0

### ISSUE THREAD

**Issue by linjunpop** [goofansu/wechat_elixir#18]
There is a version `v0.4.0-rc.0` on hex.pm, but not here.

**Comment by goofansu** [comment]
@linjunpop Yes, I'm rewriting the API and the manual, will release by the end of week.

**Comment by goofansu** [comment]
@linjunpop I'm writing a thin API wrapper to make it support multiple clients and most of the APIs, mostly inspired by https://github.com/edgurgel/tentacat. I wonder whether to publish a new break version or create a new project, what do you think?

If there is anyone using this project in production, please leave a comment. If there is few, I will choose to publish a new break version.

In the new API wrapper, I plan to support most common APIs, leaving a request function to help users easily implement uncommon APIs if they need.

**Comment by linjunpop** [comment]
@goofansu A wrapper for all WeChat's APIs? That sounds cool.

**Comment by goofansu** [comment]
@linjunpop Thanks.

It includes the most commonly used APIs, including two parts:

1. Wechat public account APIs (微信公众号API)
    Endpoint: https://api.weixin.qq.com/cgi-bin/
    Reference: https://github.com/Eric-Guo/wechat

2. Wechat mini-program APIs (微信小程序API)
    Endpoints: 
    1. https://api.weixin.qq.com/wxa/
    2. https://api.weixin.qq.com/sns/

But it doesn't include APIs like https://github.com/goofansu/wechat_elixir/blob/master/lib/wechat/datacube.ex, as there are few users using it directly.

It will only be an API thin wrapper, plugs will be moved into another repo.

**Comment by linjunpop** [comment]
> plugs will be moved into another repo.

That's what I'm hesitating about whether there should be two packages for wechat_pay or a unified one. 😸

**Comment by goofansu** [comment]
@linjunpop wechat_pay seems OK as it looks not too heavy. 

wechat_elixir needs to be splitted into three parts as they are no direct relations.
1. APIs
2. Plugs
3. Message responder DSL (I see this has been implemented, for example, https://github.com/h1u2i3/ex_wechat)

There are some benefits I can see:

1. Wraps only the APIs users want to use:

```elixir
defmodule Example.WechatAPI do
  def client do
    appid = System.get_env("WECHAT_APPID")
    secret = System.get_env("WECHAT_SECRET")
    Wechat.Client.new(appid, secret)
  end

  def users do 
    Wechat.User.users(client())
  end
end
```

2. Try multiple accounts in iex more easily

```bash
iex> client = Wechat.Client.new("appid", "secret")
...> Wechat.User.users(client)

iex> client = Wechat.Client.new("appid2", "secret2")
...> Wechat.User.users(client)
```

**Comment by goofansu** [comment]
I will merge https://github.com/goofansu/orca into this repo.
